server.port=${PORT:8083}
spring.application.name=resource-service

eureka.client.enabled=${EUREKA_ENABLED:false}
spring.cloud.discovery.enabled=${EUREKA_ENABLED:false}

management.endpoints.web.exposure.include=health,info
